name: build
on:
  push:
    branches:
      - main
    tags:
      - '!*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u slamdev --password-stdin
      - uses: actions/setup-java@v2
        with:
          java-version: 13
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: build jib --image=slamdev/hetzner-irobo:latest
