name: release
on:
  push:
    branches:
      - '!*'
    tags:
      - '*.*.*'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u slamdev --password-stdin
      - uses: actions/setup-java@v1
        with:
          java-version: 13
      - run: '"RELEASE_VERSION=${GITHUB_REF##*/}" >> $GITHUB_ENV'
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: jib --image=slamdev/hetzner-irobo:${{ env.RELEASE_VERSION }}
